# Generated by Django 2.0.4 on 2018-04-15 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('USTPricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ustcontract',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published'),
            preserve_default=False,
        ),
    ]
