# Generated by Django 2.0.4 on 2018-04-16 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USTPricing', '0002_ustcontract_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='USTResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalSize', models.FloatField(default=0)),
                ('totalSell', models.FloatField(default=0)),
                ('collateral', models.FloatField(default=0)),
                ('reward', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='ustcontract',
            name='collateral',
        ),
        migrations.RemoveField(
            model_name='ustcontract',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='ustcontract',
            name='totalSell',
        ),
        migrations.RemoveField(
            model_name='ustcontract',
            name='totalSize',
        ),
        migrations.AddField(
            model_name='ustresult',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USTPricing.USTContract'),
        ),
    ]
