# Generated by Django 2.0.4 on 2018-04-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USTPricing', '0003_auto_20180416_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ustresult',
            name='collateral',
        ),
        migrations.RemoveField(
            model_name='ustresult',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='ustresult',
            name='totalSell',
        ),
        migrations.RemoveField(
            model_name='ustresult',
            name='totalSize',
        ),
        migrations.AddField(
            model_name='ustcontract',
            name='collateral',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ustcontract',
            name='reward',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ustcontract',
            name='totalSize',
            field=models.FloatField(default=0),
        ),
    ]
