# Generated by Django 2.0.4 on 2018-04-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USTPricing', '0004_auto_20180416_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='ustcontract',
            name='evepraisalID',
            field=models.CharField(default='asdfg', max_length=6),
            preserve_default=False,
        ),
    ]
